### ISSUE TITLE
link component

### ISSUE THREAD

**Issue by sewera** [blazejsewera/blog#10]
Links should be blue with no underline, only on hover.

```css
a {
  text-decoration: none;
  color: hsl(223, 65%, 55%);
  font-weight: 400;
}

a:hover {
  text-decoration: underline;
}
```

![ss_20220909_002622](https://user-images.githubusercontent.com/18354178/189355579-2b14ffa8-2e5e-4888-9a30-7c457f652e22.jpg)
