### ISSUE TITLE
ribbon component

### ISSUE THREAD

**Issue by sewera** [blazejsewera/blog#11]
It should show up when scrolling down the page, on the right on `md` and `lg`, at the top on `sm`.

## CSS

```css
/* Ribbon in post content */
#ribbon {
  height: 420px;
}

@media (max-width: 767px) {
  #ribbon {
    height: 45px;
  }
}

#ribbon {
  position: fixed;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  right: -50px;
  top: 80px;
  box-sizing: border-box;
  width: 50px;
  height: 260px;
  padding: 15px 5px;
  background-color: hsl(0, 0%, 20%);
  color: hsl(0, 0%, 100%);
  font-size: 16px;
  z-index: 68;
  transition-property: right;
  transition-duration: 200ms;
}

#ribbon.visible {
  right: 0;
}

#ribbon #menu-ribbon-button img {
  height: 24px;
  margin: auto;
}

#ribbon .logo {
  height: 30px;
  margin: auto;
}

#ribbon span {
  writing-mode: vertical-rl;
  text-orientation: mixed;
}

#ribbon > div, #ribbon > span {
  margin: 0 auto;
}
```

![ss_20220909_002119](https://user-images.githubusercontent.com/18354178/189356321-fc371906-7606-4bf9-a12c-3cbdbae970d9.jpg)

![ss_20220909_002347](https://user-images.githubusercontent.com/18354178/189356362-9fd5ae76-5dff-44ed-a340-90dc5d484a01.jpg)
