### ISSUE TITLE
menu component

### ISSUE THREAD

**Issue by sewera** [blazejsewera/blog#12]
It should slide in from the right and cover only part of the screen on `md` and `lg`,
cover the whole screen on `sm`.

## CSS

```css
#menu {
  background-color: hsl(0, 0%, 20%);
  position: fixed;
  top: 0;
  right: -700px;
  height: 100vh;
  width: 700px;
  padding: 50px;
  box-sizing: border-box;
  z-index: 69;
  transition-property: right;
  transition-duration: 400ms;
}
#menu.visible {
  right: 0;
}

#menu ul {
  font-size: 36px;
}

#menu a {
  color: hsl(0, 0%, 75%);
  font-weight: 400;
  transition-property: color;
  transition-duration: 300ms;
}
#menu a:hover {
  text-decoration: none;
  color: hsl(0, 0%, 100%);
}

#menu-close-button {
  position: absolute;
  top: 50px;
  left: 50px;
}

@media (min-width: 768px) and (max-width: 1300px) {
  #menu {
    width: 550px;
    right: -550px;
  }

  #menu ul {
    font-size: 30px;
  }
}

@media (max-width: 767px) {
  #menu {
    top: 0;
    right: -100vw;
    width: 100vw;
    padding: 40px;
    transition-property: right;
    transition-duration: 400ms;
  }
  #menu.visible {
    right: 0;
  }

  #menu > div.center-y-flex {
    width: 100%;
  }

  #menu ul {
    font-size: 24px;
  }

  #menu h2 {
    max-width: 200px;
  }

  #menu-links, #menu-links > li, #menu-links > li > a {
    width: 100%;
  }

  #menu-links > li > a {
    display: inline-block;
    margin-bottom: 10px;
  }

  #menu-close-button {
    left: auto;
    top: 40px;
    right: 40px;
  }
}
```

`md`:

![ss_20220909_002444](https://user-images.githubusercontent.com/18354178/189356838-f4863ce9-e963-4f7b-98cf-984b3c5beeac.jpg)

`lg`:

![ss_20220909_002504](https://user-images.githubusercontent.com/18354178/189356920-d89e1b87-949b-4ed2-9021-d4cd859beacc.jpg)

`sm`:

![ss_20220909_002413](https://user-images.githubusercontent.com/18354178/189356880-9cc8a2cc-8fd4-4877-9984-714c5d23227e.jpg)
