### ISSUE TITLE
page overlay

### ISSUE THREAD

**Issue by sewera** [blazejsewera/blog#13]
Posts, both the title banner and content have to be properly contained.

```css
.post-content {
  color: hsl(0, 0%, 30%);
  margin: 30px auto;
  width: 45rem;
}

.margin-bottom-header {
  margin-bottom: 120px;
}

/* For smaller screens */
@media (min-width: 768px) and (max-width: 1300px) {
  .post-content {
    margin: 20px auto;
  }

  .margin-bottom-header {
    margin-bottom: 80px;
  }
}

@media (max-width: 767px) {
  .post-content {
    margin: 10px 0;
    min-width: 1px;
    width: 100vw;
    box-sizing: border-box;
  }

  .margin-bottom-header {
    margin-bottom: 40px;
  }
}
```
