### ISSUE TITLE
code component

### ISSUE THREAD

**Issue by sewera** [blazejsewera/blog#14]
- [x] inline code
- [x] code block

## Inline code

```css
.post-content code {
  font-family: "Suisse Int'l Mono", monospace;
  font-size: 85%;
  padding: 0.2rem 0.4rem;
  border-radius: 6px;
  white-space: pre;
  word-break: break-all;
  background-color: hsla(210, 12%, 12%, 0.05);
}
```

![ss_20220909_152619](https://user-images.githubusercontent.com/18354178/189360543-5f204bc9-b5e3-415c-a318-ce7a91e6e8d9.jpg)

## Code block

```css
.post-content code.block {
  max-width: 35rem;
  margin: 1rem 4rem 4rem 5.2rem;
  padding-left: 0.8rem;
  display: block;
  overflow-x: auto;
  border-left: 8px solid hsl(0, 0%, 90%);
  border-radius: 0;
  background-color: hsl(210, 29%, 97%);
}

.post-content p > code.block {
  margin: 1rem 2rem 2rem 1.2rem;
}

@media (max-width: 767px) {
  .post-content code.block {
    margin: 1rem 30px 4rem 30px;
  }
}
```

![ss_20220909_152705](https://user-images.githubusercontent.com/18354178/189360695-67c11230-13d6-4947-b0ed-b19f8bead245.jpg)
