### ISSUE TITLE
set up Suisse fonts

### ISSUE THREAD

**Issue by sewera** [blazejsewera/blog#4]
- [ ] add font definitions in css
- [ ] wire up [custom fonts in Tailwind](https://tailwindcss.com/docs/font-family#using-custom-values)

```css
@font-face {
  font-family: "Suisse Int'l";
  src: url("/static/www/fonts/SuisseIntl-Book-WebS.woff2") format("woff2"),
       url("/static/www/fonts/SuisseIntl-Book-WebS.woff") format("woff");
  font-weight: 400;
  font-display: swap;
}

@font-face {
  font-family: "Suisse Int'l";
  src: url("/static/www/fonts/SuisseIntl-SemiBold-WebS.woff2") format("woff2"),
       url("/static/www/fonts/SuisseIntl-SemiBold-WebS.woff") format("woff");
  font-weight: 600;
  font-display: swap;
}

@font-face {
  font-family: "Euclid Square";
  src: url("/static/www/fonts/EuclidSquare-Medium-WebS.woff2") format("woff2"),
       url("/static/www/fonts/EuclidSquare-Medium-WebS.woff") format("woff");
  font-weight: 500;
  font-display: swap;
}

@font-face {
  font-family: "Suisse Int'l Mono";
  src: url('/static/www/fonts/SuisseIntlMono-Regular-WebS.woff2')
      format('woff2'),
    url('/static/www/fonts/SuisseIntlMono-Regular-WebS.woff') format('woff');
  font-weight: 400;
  font-display: swap;
}

@font-face {
  font-family: "Suisse Int'l";
  src: url('/static/www/fonts/SuisseIntl-BookItalic-WebS.woff2') format('woff2'),
    url('/static/www/fonts/SuisseIntl-BookItalic-WebS.woff') format('woff');
  font-weight: 400;
  font-display: swap;
  font-style: italic;
}
```
