### ISSUE TITLE
image component

### ISSUE THREAD

**Issue by sewera** [blazejsewera/blog#8]
Images should be displayed either with width
aligned to text width,
or a bit wider (first image).

If an image is wider than taller (`width > height`),
it should be displayed wider.

Else, (`width <= height`), display it aligned to text (second image).

Prepare a third, `huge` size, much wider than the text.

This property should be overridable, i.e.,
if a user specifies `narrow`, or `wide`,
the automatic adjustment should be manually overridden.

E.g.,
```jsx
<Figure caption="Figure caption" alt="Figure alt" size="narrow" />
```

Aligned to text width:

![ss_20220909_143240](https://user-images.githubusercontent.com/18354178/189350608-a02cb009-7854-4a53-8310-e716c6a1a588.jpg)

Wider than text:

![ss_20220909_143321](https://user-images.githubusercontent.com/18354178/189350733-3684fd1c-e754-450b-a671-510292e92c09.jpg)

## CSS

```css
.post-content img {
  max-width: 37rem;
  display: block;
  margin: 0 auto;
}
.post-content img.wide {
  max-width: 45rem;
}

.post-content figure {
  margin: 1rem 0 2rem 0;
}

.post-content figcaption {
  font-size: 16px;
  margin-top: 8px;
  text-align: center;
}

@media (min-width: 768px) and (max-width: 1300px) {
  .post-content figure {
    margin: 16px 0;
  }

  .post-content figcaption {
    font-size: 14px;
  }
}

@media (max-width: 767px) {
  .post-content figure {
    margin: 16px 0;
  }

  .post-content figcaption {
    font-size: 12px;
  }

  .post-content img {
    max-width: calc(100vw - 60px);
  }

  .post-content img.wide {
    max-width: unset;
    width: 100vw;
  }
}
```

If in doubt, consult [Apple Newsroom](https://www.apple.com/newsroom/)

[Apple celebrates America's parks article](https://www.apple.com/newsroom/2022/08/apple-celebrates-americas-parks/):

![ss_20220909_144004](https://user-images.githubusercontent.com/18354178/189352025-3f8dc9bf-13f8-4d91-9b85-c22612e31eec.jpg)

![ss_20220909_144110](https://user-images.githubusercontent.com/18354178/189352168-66cdd5b4-96f5-4d9b-a2ac-55c4100c6612.jpg)
