### ISSUE TITLE
paragraph component

### ISSUE THREAD

**Issue by sewera** [blazejsewera/blog#9]
Text should flow naturally for the eyes. Therefore max-width is necessary.

Implement:
- [ ] normal text;
- [ ] bold text;
- [ ] italic text;
- [ ] `ul`;
- [ ] `ol`.

```css
.post-content {
  color: hsl(0, 0%, 30%);
  margin: 30px auto;
  width: 45rem;
}

.post-content i,
.post-content em {
  font-family: "Suisse Int'l", 'Helvetica Neue', 'Helvetica', 'Liberation Sans',
    'Arial', sans-serif;
  font-style: italic;
  font-weight: 400;
}

.post-content b,
.post-content strong {
  font-family: "Suisse Int'l", 'Helvetica Neue', 'Helvetica', 'Liberation Sans',
    'Arial', sans-serif;
  font-style: normal;
  font-weight: 600;
}

.post-content p,
.post-content > ul,
.post-content > ol {
  max-width: 37rem;
  margin: 0 4rem 2rem 4rem;
  line-height: 1.55;
  letter-spacing: 0.018em;
}

.margin-bottom-header {
  margin-bottom: 120px;
}

/* For smaller screens */
@media (min-width: 768px) and (max-width: 1300px) {
  .post-content {
    margin: 20px auto;
  }

  .post-content h2 {
    font-size: 36px;
  }
  .post-content h3 {
    font-size: 24px;
  }
  .post-content h4 {
    font-size: 20px;
  }

  .post-content p,
  .post-content > ul,
  .post-content > ol {
    line-height: 1.6;
    letter-spacing: 0.021em;
  }

  .margin-bottom-header {
    margin-bottom: 80px;
  }
}

@media (max-width: 767px) {
  .post-content {
    margin: 10px 0;
    min-width: 1px;
    width: 100vw;
    box-sizing: border-box;
  }

  .post-content p,
  .post-content > ul,
  .post-content > ol {
    margin: 0 30px 2rem 30px;
    max-width: 37rem;
    line-height: 1.6;
    letter-spacing: 0.021em;
  }

  .post-content code.block {
    margin: 1rem 30px 4rem 30px;
  }

  .margin-bottom-header {
    margin-bottom: 40px;
  }
}
```

normal text:

![ss_20220909_145807](https://user-images.githubusercontent.com/18354178/189355264-7157f400-cdf1-4157-a7f4-b44615beadd9.jpg)

bold text:

![ss_20220909_145847](https://user-images.githubusercontent.com/18354178/189355366-415503e2-de4d-4246-9fc8-689247a5a87d.jpg)

italics:

![ss_20220909_153005](https://user-images.githubusercontent.com/18354178/189361373-f19d537f-30f7-4c0f-b864-4a237cd55ac8.jpg)

`ol` and `ul`:

![ss_20220909_152802](https://user-images.githubusercontent.com/18354178/189361027-542e075a-df45-41c5-96bb-a1401411b3a2.jpg)
